# Generated by Django 4.0.5 on 2024-03-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_anagramhuntscore_created_mathfactsscore_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagramhuntscore',
            name='max_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anagramhuntscore',
            name='time_left',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathfactsscore',
            name='max_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathfactsscore',
            name='time_left',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
