# Generated by Django 4.0.5 on 2024-03-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_anagramhuntscore_max_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagramhuntscore',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathfactsscore',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
